In [1]:
import numpy as np

In [10]:
a = np.array([[1,230.1,37.8,69.2], [1,44.5,39.3,45.1], [1,17.2,45.9,69.3], [1,151.5,41.3,58.5], [1,180.8,10.8,58.4]])

In [7]:
mean_data = np.array([
[6.0, 315.0, 4.8123788544375692e-06],
[6.5, 0.0, 2.259217450023793e-06],
[6.5, 45.0, 9.2823565008402673e-06],
[6.5, 90.0, 8.309270169336028e-06],
[6.5, 135.0, 6.4709418114245381e-05],
[6.5, 180.0, 1.7227922423558414e-05],
[6.5, 225.0, 1.2308522579848724e-05],
[6.5, 270.0, 2.6905672894824344e-05],
[6.5, 315.0, 2.2727114437176048e-05]])

In [9]:
b = np.array([22.1,10.4,9.3,18.5,12.8])

In [12]:
 c = np.matmul(a.T,a)

In [13]:
c

array([[  5.00000000e+00,   6.24100000e+02,   1.75100000e+02,
          3.00500000e+02],
       [  6.24100000e+02,   1.10862990e+05,   1.94457000e+04,
          3.85433000e+04],
       [  1.75100000e+02,   1.94457000e+04,   6.90247000e+03,
          1.06158300e+04],
       [  3.00500000e+02,   3.85433000e+04,   1.06158300e+04,
          1.84579500e+04]])

In [14]:
d = np.linalg.inv(c)

In [15]:
d

array([[  9.95951210e+00,  -2.06193689e-03,  -3.54325183e-02,
         -1.37459141e-01],
       [ -2.06193689e-03,   4.78625205e-05,   1.69354407e-04,
         -1.63777941e-04],
       [ -3.54325183e-02,   1.69354407e-04,   1.93426314e-03,
         -8.89254474e-04],
       [ -1.37459141e-01,  -1.63777941e-04,  -8.89254474e-04,
          3.14548411e-03]])

In [16]:
e = np.matmul(a.T,b)

In [17]:
e

array([    73.1 ,  10824.96,   2573.26,   4472.62])

In [18]:
f = np.matmul(d,e)

In [19]:
f

array([-0.25963306,  0.07065871,  0.24320221, -0.04088068])

In [30]:
answer = (0 + (250 * f[1]) + (50 * f[2]) + (50 * f[3]))

In [31]:
answer

27.780754382047526