In [2]:
import numpy as np
import h5py
import matplotlib.pyplot as plt

In [3]:
np.random.seed(1)


In [4]:
def pad(X,pad):
    """
    X is an array of shape(m,n_H,n_W,n_C) 
    where m =  no of images
    n_H = height of image
    n_W = width of image
    n_C = no of channels
    padding adds an equal amount of pad at the egdes of the image across all channels
    """
    X_pad = X_pad = np.pad(X,((0,0),(pad,pad),(pad,pad),(0,0)),'constant',constant_values = 0)
    return X_pad

In [7]:
x = np.random.randn(4, 3, 3, 2)

In [8]:
x

array([[[[ 1.62434536, -0.61175641],
         [-0.52817175, -1.07296862],
         [ 0.86540763, -2.3015387 ]],

        [[ 1.74481176, -0.7612069 ],
         [ 0.3190391 , -0.24937038],
         [ 1.46210794, -2.06014071]],

        [[-0.3224172 , -0.38405435],
         [ 1.13376944, -1.09989127],
         [-0.17242821, -0.87785842]]],


       [[[ 0.04221375,  0.58281521],
         [-1.10061918,  1.14472371],
         [ 0.90159072,  0.50249434]],

        [[ 0.90085595, -0.68372786],
         [-0.12289023, -0.93576943],
         [-0.26788808,  0.53035547]],

        [[-0.69166075, -0.39675353],
         [-0.6871727 , -0.84520564],
         [-0.67124613, -0.0126646 ]]],


       [[[-1.11731035,  0.2344157 ],
         [ 1.65980218,  0.74204416],
         [-0.19183555, -0.88762896]],

        [[-0.74715829,  1.6924546 ],
         [ 0.05080775, -0.63699565],
         [ 0.19091548,  2.10025514]],

        [[ 0.12015895,  0.61720311],
         [ 0.30017032, -0.35224985],
         [-1.14251

In [11]:
pad(x,1)

array([[[[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ]],

        [[ 0.        ,  0.        ],
         [ 1.62434536, -0.61175641],
         [-0.52817175, -1.07296862],
         [ 0.86540763, -2.3015387 ],
         [ 0.        ,  0.        ]],

        [[ 0.        ,  0.        ],
         [ 1.74481176, -0.7612069 ],
         [ 0.3190391 , -0.24937038],
         [ 1.46210794, -2.06014071],
         [ 0.        ,  0.        ]],

        [[ 0.        ,  0.        ],
         [-0.3224172 , -0.38405435],
         [ 1.13376944, -1.09989127],
         [-0.17242821, -0.87785842],
         [ 0.        ,  0.        ]],

        [[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ]]],


       [[[ 0.        ,  0.        ],
         [ 0.        ,  0.

In [12]:
# GRADED FUNCTION: conv_single_step

def conv_single_step(a_slice_prev, W, b):
    """
    Apply one filter defined by parameters W on a single slice (a_slice_prev) of the output activation 
    of the previous layer.
    
    Arguments:
    a_slice_prev -- slice of input data of shape (f, f, n_C_prev)
    W -- Weight parameters contained in a window - matrix of shape (f, f, n_C_prev)
    b -- Bias parameters contained in a window - matrix of shape (1, 1, 1)
    
    Returns:
    Z -- a scalar value, result of convolving the sliding window (W, b) on a slice x of the input data
    """

    ### START CODE HERE ### (≈ 2 lines of code)
    # Element-wise product between a_slice and W. Do not add the bias yet.
    s = np.multiply(a_slice_prev,W) + b
    # Sum over all entries of the volume s.
    Z = np.sum(s)
    # Add bias b to Z. Cast b to a float() so that Z results in a scalar value.
    ### END CODE HERE ###

    return Z

In [13]:
a_slice_prev = np.random.randn(4, 4, 3)

In [16]:
a_slice_prev

array([[[ 0.16003707,  0.87616892,  0.31563495],
        [-2.02220122, -0.30620401,  0.82797464],
        [ 0.23009474,  0.76201118, -0.22232814],
        [-0.20075807,  0.18656139,  0.41005165]],

       [[ 0.19829972,  0.11900865, -0.67066229],
        [ 0.37756379,  0.12182127,  1.12948391],
        [ 1.19891788,  0.18515642, -0.37528495],
        [-0.63873041,  0.42349435,  0.07734007]],

       [[-0.34385368,  0.04359686, -0.62000084],
        [ 0.69803203, -0.44712856,  1.2245077 ],
        [ 0.40349164,  0.59357852, -1.09491185],
        [ 0.16938243,  0.74055645, -0.9537006 ]],

       [[-0.26621851,  0.03261455, -1.37311732],
        [ 0.31515939,  0.84616065, -0.85951594],
        [ 0.35054598, -1.31228341, -0.03869551],
        [-1.61577235,  1.12141771,  0.40890054]]])

In [28]:
a_slice_prev[0:3,1:4,:]

array([[[-2.02220122, -0.30620401,  0.82797464],
        [ 0.23009474,  0.76201118, -0.22232814],
        [-0.20075807,  0.18656139,  0.41005165]],

       [[ 0.37756379,  0.12182127,  1.12948391],
        [ 1.19891788,  0.18515642, -0.37528495],
        [-0.63873041,  0.42349435,  0.07734007]],

       [[ 0.69803203, -0.44712856,  1.2245077 ],
        [ 0.40349164,  0.59357852, -1.09491185],
        [ 0.16938243,  0.74055645, -0.9537006 ]]])

In [26]:
(n_H,n_W,n_C) = a_slice_prev.shape

In [29]:
def conv_forward(A_prev, W, b, hparameters):
    """
    Implements the forward propagation for a convolution function
    
    Arguments:
    A_prev -- output activations of the previous layer, numpy array of shape (m, n_H_prev, n_W_prev, n_C_prev)
    W -- Weights, numpy array of shape (f, f, n_C_prev, n_C)
    b -- Biases, numpy array of shape (1, 1, 1, n_C)
    hparameters -- python dictionary containing "stride" and "pad"
        
    Returns:
    Z -- conv output, numpy array of shape (m, n_H, n_W, n_C)
    cache -- cache of values needed for the conv_backward() function
    """
    
    ### START CODE HERE ###
    # Retrieve dimensions from A_prev's shape (≈1 line)  
    (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape
    
    # Retrieve dimensions from W's shape (≈1 line)
    (f, f, n_C_prev, n_C) = W.shape

    # Retrieve information from "hparameters" (≈2 lines)
    stride = hparameters['stride']
    pad = hparameters['pad']
    
    # Compute the dimensions of the CONV output volume using the formula given above. Hint: use int() to floor. (≈2 lines)
    n_H = int((n_H_prev - f + 2 * pad) / stride) + 1
    n_W = int((n_W_prev - f + 2 * pad) / stride) + 1
    
    # Initialize the output volume Z with zeros. (≈1 line)
    Z = np.zeros((m, n_H, n_W, n_C))
    
    # Create A_prev_pad by padding A_prev
    A_prev_pad = zero_pad(A_prev, pad)
    
    for i in range(m):                                 # loop over the batch of training examples
        a_prev_pad = A_prev_pad[i]                     # Select ith training example's padded activation
        for h in range(n_H):                           # loop over vertical axis of the output volume
            for w in range(n_W):                       # loop over horizontal axis of the output volume
                for c in range(n_C):                   # loop over channels (= #filters) of the output volume
                    # Find the corners of the current "slice" (≈4 lines)
                    vert_start = h * stride
                    vert_end = vert_start + f
                    horiz_start = w * stride
                    horiz_end = horiz_start + f
                    # Use the corners to define the (3D) slice of a_prev_pad (See Hint above the cell). (≈1 line)
                    a_slice_prev = a_prev_pad[vert_start:vert_end, horiz_start:horiz_end, :]
                    # Convolve the (3D) slice with the correct filter W and bias b, to get back one output neuron. (≈1 line)
                    Z[i, h, w, c] = conv_single_step(a_slice_prev, W[...,c], b[...,c])
                                        
    ### END CODE HERE ###

    # Making sure your output shape is correct
    assert(Z.shape == (m, n_H, n_W, n_C))
    
    # Save information in "cache" for the backprop
    cache = (A_prev, W, b, hparameters)
    
    return Z, cache