In [3]:
import numpy as np
from nltk.tokenize import word_tokenize

In [8]:
filename = 'metamorphosis.txt'
file = open(filename,'rt')
text = file.read()
file.close()


In [10]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/abhinavverma/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [11]:
tokens = word_tokenize(text)

In [12]:
# remove all tokens that are not alphabetic
words = [word for word in tokens if word.isalpha()]
print(words[:100])

['One', 'morning', 'when', 'Gregor', 'Samsa', 'woke', 'from', 'troubled', 'dreams', 'he', 'found', 'himself', 'transformed', 'in', 'his', 'bed', 'into', 'a', 'horrible', 'vermin', 'He', 'lay', 'on', 'his', 'back', 'and', 'if', 'he', 'lifted', 'his', 'head', 'a', 'little', 'he', 'could', 'see', 'his', 'brown', 'belly', 'slightly', 'domed', 'and', 'divided', 'by', 'arches', 'into', 'stiff', 'sections', 'The', 'bedding', 'was', 'hardly', 'able', 'to', 'cover', 'it', 'and', 'seemed', 'ready', 'to', 'slide', 'off', 'any', 'moment', 'His', 'many', 'legs', 'pitifully', 'thin', 'compared', 'with', 'the', 'size', 'of', 'the', 'rest', 'of', 'him', 'waved', 'about', 'helplessly', 'as', 'he', 'looked', 'What', 'happened', 'to', 'me', 'he', 'thought', 'It', 'was', 'a', 'dream', 'His', 'room', 'a', 'proper', 'human', 'room']


# Filter out stop words
### Stop words are common words like 'a' 'an'  and throw off the word embedding matrix . It makes sense to remove them

In [14]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/abhinavverma/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [15]:
## We use the popular stopwords defined in the nltk corpus. 
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [16]:
stop_words = set(stopwords.words('english'))

In [17]:
words_clean = [w for w in words if not w in stop_words]

In [19]:
len(words_clean)

10574

# Index the words to numbers and backwards for reference

In [24]:
word2idx = {}
idx2word = {}
idx2wordlist = []

In [25]:
for i,word in enumerate(words_clean):
    word2idx[word] = i
    idx2word[i] = word
    idx2wordlist.append(word)

# Bigrams and Markov techniques

In [27]:
u = [6,0,-2]
v = [0,8,0]
np.cross(u,v)

array([16,  0, 48])

In [28]:
u = np.array([[1,-3,3],[3,-5,3],[6,-6,4]])

In [29]:
np.linalg.eig(u)

(array([ 4., -2., -2.]), array([[-0.40824829, -0.81034214,  0.1932607 ],
        [-0.40824829, -0.31851537, -0.59038328],
        [-0.81649658,  0.49182677, -0.78364398]]))

In [32]:
A = np.array([[0,1],[1,1]])
B = np.array([[5,6],[2,1]])
np.dot(A,B)

array([[2, 1],
       [7, 7]])

In [33]:
from nltk.stem.porter import PorterStemmer

In [34]:
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in tokens]
print(stemmed[:100])

['one', 'morn', ',', 'when', 'gregor', 'samsa', 'woke', 'from', 'troubl', 'dream', ',', 'he', 'found', 'himself', 'transform', 'in', 'hi', 'bed', 'into', 'a', 'horribl', 'vermin', '.', 'He', 'lay', 'on', 'hi', 'armour-lik', 'back', ',', 'and', 'if', 'he', 'lift', 'hi', 'head', 'a', 'littl', 'he', 'could', 'see', 'hi', 'brown', 'belli', ',', 'slightli', 'dome', 'and', 'divid', 'by', 'arch', 'into', 'stiff', 'section', '.', 'the', 'bed', 'wa', 'hardli', 'abl', 'to', 'cover', 'it', 'and', 'seem', 'readi', 'to', 'slide', 'off', 'ani', 'moment', '.', 'hi', 'mani', 'leg', ',', 'piti', 'thin', 'compar', 'with', 'the', 'size', 'of', 'the', 'rest', 'of', 'him', ',', 'wave', 'about', 'helplessli', 'as', 'he', 'look', '.', '``', 'what', "'s", 'happen', 'to']


# We will be implementing the Porter Stemmer algorithm from scratch to develop the intuition and the working knowledge of the lemmatization step

In [38]:
## To find if given letter is a consonant
def isCons(letter):
    
    if letter == 'a' or letter == 'e' or letter == 'i' or letter == 'o'or letter == 'u':
        
        
        return False
    else:
        
        return True

In [ ]:
##def step 1a
def step1a(word):
    if word.endswith('sses'):
        word = word.replace()