In [28]:
import numpy as np

In [149]:
class Tensor:
    def __init__(self,data,autograd=False,creators=None,creation_ops=None,id=None):
        self.data = np.array(data)
        self.creators = creators
        self.creation_ops = creation_ops
        self.autograd = autograd
        self.children = {}
        if(id is None):
            id = np.random.randint(0,100000)
        self.id = id
        
        if(creators is not None):
            for c in creators:
                if(self.id not in c.children):
                    c.children[self.id] = 1
                else:
                    c.children[self.id] += 1
        
        
        self.grad = None
    def all_children_grads_accounted_for(self):
        for id,cnt in self.children.items():
            if(cnt != 0):
                return False
        return True
    
    def backward(self,grad=None, grad_origin=None):
        if(self.autograd):
            if(grad is None):
                grad = FloatTensor(np.ones_like(self.data))
            
            if(grad_origin is not None):
                if(self.children[grad_origin.id] == 0):
                    raise Exception("cannot backprop more than once")
                else:
                    self.children[grad_origin.id] -= 1

            if(self.grad is None):
                self.grad = grad
            else:
                self.grad += grad
            
            # grads must not have grads of their own
            assert grad.autograd == False
            
            # only continue backpropping if there's something to
            # backprop into and if all gradients (from children)
            # are accounted for override waiting for children if
            # "backprop" was called on this variable directly
            if(self.creators is not None and 
               (self.all_children_grads_accounted_for() or 
                grad_origin is None)):

                if(self.creation_ops == "add"):
                    self.creators[0].backward(self.grad,self)
                    self.creators[1].backward(self.grad,self)
                if(self.creation_ops == "neg"):
                    self.creators[0].backward(self.grad.__neg__())
                if(self.creation_ops == "mul"):
                    new = self.grad * self.creators[1]
                    self.creators[0].backward(new , self)
                    new = self.grad * self.creators[0]
                    self.creators[1].backward(new, self)
                if(self.creation_ops == "mm"):
                    c0 = self.creators[0]
                    c1 = self.creators[1]
                    new = self.grad.mm(c1.transpose())
                    c0.backward(new)
                    new = self.grad.transpose().mm(c0).transpose()
                    c1.backward(new)
                if(self.creation_ops == "transpose"):
                    self.creators[0].backward(self.grad.transpose())
                
                if(self.creation_ops == "sub"):
                    self.creators[0].backward(Tensor(self.grad.data), self)
                    self.creators[1].backward(Tensor(self.grad.__neg__().data), self)
                if("sum" in self.creation_ops):
                    dim = int(self.creation_ops.split("_")[1])
                    self.creators[0].backward(self.grad.expand(dim,
                                                               self.creators[0].data.shape[dim]))
                if("expand" in self.creation_ops):
                    dim = int(self.creation_ops.split("_")[1])
                    self.creators[0].backward(self.grad.sum(dim))
                    
    def __add__(self,other):
        if(self.autograd and other.autograd):
            return Tensor(self.data + other.data,
                          autograd=True,
                          creators=[self,other],
                          creation_ops="add")
        return Tensor(self.data + other.data,creators=[self,other],creation_ops="add")
    def __neg__(self):
        if(self.autograd):
            return Tensor(self.data * -1,autograd=True,creators=[self],creation_ops="neg")
        return Tensor(self.data * -1)
    
    def __sub__(self, other):
        if(self.autograd and other.autograd):
            return Tensor(self.data - other.data,
                          autograd=True,
                          creators=[self,other],
                          creation_ops="sub")
        return Tensor(self.data - other.data)
    
    def __mul__(self, other):
        if(self.autograd and other.autograd):
            return Tensor(self.data * other.data,
                          autograd=True,
                          creators=[self,other],
                          creation_ops="mul")
        return Tensor(self.data * other.data)
    
    def sum(self, dim):
        if(self.autograd):
            return Tensor(self.data.sum(dim),
                          autograd=True,
                          creators=[self],
                          creation_ops="sum_"+str(dim))
        return Tensor(self.data.sum(dim))
    def expand(self,dim,copies):
        trans_cmd = list(range(0,len(self.data.shape)))
        trans_cmd = trans_cmd.insert(dim,len(self.data.shape))
        new_data =  self.data.repeat(copies).reshape(list(self.data.shape) + [copies]).transpose(trans_cmd)
        if(self.autograd):
            return Tensor(new_data,
                          autograd=True,
                          creators=[self],
                          creation_ops="expand_"+str(dim))
        return Tensor(new_data)
    
    def mm(self, x):
        if(self.autograd):
            return Tensor(self.data.dot(x.data),
                          autograd=True,
                          creators=[self,x],
                          creation_ops="mm")
        return Tensor(self.data.dot(x.data))
    def transpose(self):
        if(self.autograd):
            return Tensor(self.data.transpose(),
                          autograd=True,
                          creators=[self],
                          creation_ops="transpose")
        
        return Tensor(self.data.transpose())
    
    def __repr__(self):
        return str(self.data.__repr__())
    def __str__(self):
        return str(self.data.__str__())

In [150]:
pos_tensor = Tensor([2,3,4,5,6],autograd=True)
-pos_tensor
pos_tensor.children

{7877: 1}

In [151]:
a = Tensor([1,2,3,4,5], autograd=True)
b = Tensor([2,2,2,2,2], autograd=True)
c = Tensor([5,4,3,2,1], autograd=True)

d = a + b
e = b + c
f = d + e

f.backward(Tensor(np.array([2,2,2,2,2])))

print(b.grad.data == np.array([2,2,2,2,2]))

[False False False False False]


In [152]:
d.children

{24675: 0}

In [147]:
z.creators

[array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2])]

In [17]:
z.backward(Tensor(np.array([1,1,1,1,1])))

In [19]:
b.grad

array([1, 1, 1, 1, 1])

In [36]:
y  = z + b

In [22]:
y.creators

[array([3, 3, 3, 3, 3]), array([2, 2, 2, 2, 2])]

In [26]:
a.grad

array([1, 1, 1, 1, 1])

In [42]:
a.children.items()

dict_items([(64833, 1), (89815, 1)])

In [41]:
c = a + y

In [100]:
list(range(0,len(re.shape)))

[0, 1]

In [92]:
re = np.array([[1,2,3],[4,5,6]])

In [93]:
re.repeat(4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6])

In [117]:
re.repeat(4).reshape(list(re.shape) + [4])

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]]])

In [124]:
np.arange(1,11)/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Vanilla neural net using just numpy

In [125]:
import numpy
np.random.seed(0)

data = np.array([[0,0],[0,1],[1,0],[1,1]])
target = np.array([[0],[1],[0],[1]])

weights_0_1 = np.random.rand(2,3)
weights_1_2 = np.random.rand(3,1)

for i in range(10):
    
    # Predict
    layer_1 = data.dot(weights_0_1)
    layer_2 = layer_1.dot(weights_1_2)
    
    # Compare
    diff = (layer_2 - target)
    sqdiff = (diff * diff)
    loss = sqdiff.sum(0) # mean squared error loss

    # Learn: this is the backpropagation piece
    layer_1_grad = diff.dot(weights_1_2.transpose())
    weight_1_2_update = layer_1.transpose().dot(diff)
    weight_0_1_update = data.transpose().dot(layer_1_grad)
    
    weights_1_2 -= weight_1_2_update * 0.1
    weights_0_1 -= weight_0_1_update * 0.1
    print(loss[0])

5.066439994622395
0.4959907791902342
0.4180671892167177
0.35298133007809646
0.2972549636567377
0.2492326038163328
0.20785392075862477
0.17231260916265176
0.14193744536652986
0.11613979792168384


## Neural network using our Tensor class

In [154]:
import numpy
np.random.seed(0)

data = Tensor(np.array([[0,0],[0,1],[1,0],[1,1]]), autograd=True)
target = Tensor(np.array([[0],[1],[0],[1]]), autograd=True)

w = list()
w.append(Tensor(np.random.rand(2,3), autograd=True))
w.append(Tensor(np.random.rand(3,1), autograd=True))

for i in range(10):

    # Predict
    pred = data.mm(w[0]).mm(w[1])
    
    # Compare
    loss = ((pred - target)*(pred - target)).sum(0)
    
    # Learn
    
    loss_grad = Tensor(np.ones_like(loss.data))
    
    loss.backward(loss_grad)

    for w_ in w:
        w_.data -= w_.grad.data * 0.1
        w_.grad.data *= 0

    print(loss)

[0.58128304]
[0.48988149]
[0.41375111]
[0.34489412]
[0.28210124]
[0.2254484]
[0.17538853]
[0.1324231]
[0.09682769]
[0.06849361]
