# First we will begin with a basic review of numpy

In [48]:
import numpy as np

In [2]:
a = np.arange(5)

In [4]:
b = np.arange(10,15)

In [5]:
a.dot(b)

130

In [7]:
np.sum(a*b)

130

In [8]:
a*b

array([ 0, 11, 24, 39, 56])

In [9]:
row_vector = np.array([[1, 3, 2]])

In [10]:
col_vector = np.array([[2], [0], [1]])

In [11]:
row_vector.dot(col_vector)

array([[4]])

In [12]:
col_vector.dot(row_vector)

array([[2, 6, 4],
       [0, 0, 0],
       [1, 3, 2]])

In [14]:
col_vector.ravel(),row_vector.ravel()

(array([2, 0, 1]), array([1, 3, 2]))

In [15]:
np.outer(col_vector.ravel(),row_vector.ravel())

array([[2, 6, 4],
       [0, 0, 0],
       [1, 3, 2]])

# Now onto the real stuff
### Comparing word embeddings to fill in the blank

In [65]:
import sys,random,math
from collections import Counter
from nltk import word_tokenize

In [66]:
#Add a seed for randomizing choice which will be explained later
np.random.seed(1)

In [88]:
#This is a list of movie reviews of Imdb file will be uploaded to github later.Example from Andrew Trask's book Grokking
#Deep Learning

f = open('reviews.txt')
raw_reviews = f.readlines()
f.close()

In [70]:
#tokens = word_tokenize(raw_reviews)

In [89]:
#tokens
#split the review array into small arrays of words of each sentence

tokens = list(map(lambda x:(x.split(" ")),raw_reviews))

In [90]:
wordcnt = Counter()

In [91]:
for sent in tokens:
    for word in sent:
        wordcnt[word] -= 1

In [92]:
# String operations to remove punctuations
import string

In [75]:
## We use the popular stopwords defined in the nltk corpus. 
from nltk.corpus import stopwords
stop_words = stopwords.words('english')


In [76]:
stop_words = set(stopwords.words('english'))

In [78]:
tokens = [w for w in tokens if w not in stop_words]

In [79]:
for word in tokens:
    wordcnt[word] -= 1

In [93]:
vocab = list(set(map(lambda x:x[0],wordcnt.most_common())))

In [94]:
len(vocab)

74075

### Create word to index and reverse dictionary

In [95]:
word2index = {}
index2word = {}
for i,word in enumerate(vocab):
    word2index[word]=i
    index2word[i]=word

In [96]:
index2word[6085],word2index['scopes']

('instigation', 9357)

In [97]:
concatenated = list()
input_dataset = list()

In [98]:
for sent in tokens:
    sent_indices = list()
    for word in sent:
        try:
            sent_indices.append(word2index[word])
            concatenated.append(word2index[word])
        except:
            ""
    input_dataset.append(sent_indices)
    

In [102]:
#concatenated is a list of all the indices of the vocab
#input_dataset is a list of sentences with indices of words replacing the actual words
concatenated = np.array(concatenated)
random.shuffle(input_dataset)

In [ ]:
alpha, iterations = (0.05, 2)
hidden_size,window,negative = (50,2,5)
