In [1]:
import numpy as np


In [2]:
height = 4
width = 6
world = np.zeros((height, width))

In [3]:
initial_position = [0, 0]
velocity = [0, 1]

In [2]:
a = "hello"
f"{a}"

'hello'

In [3]:
def softmax(x_):
    x = np.atleast_2d(x_)
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1)

In [4]:
word_vects = {}
word_vects['yankees'] = np.array([[0.,0.,0.]])
word_vects['bears'] = np.array([[0.,0.,0.]])
word_vects['braves'] = np.array([[0.,0.,0.]])
word_vects['red'] = np.array([[0.,0.,0.]])
word_vects['socks'] = np.array([[0.,0.,0.]])
word_vects['lose'] = np.array([[0.,0.,0.]])
word_vects['defeat'] = np.array([[0.,0.,0.]])
word_vects['beat'] = np.array([[0.,0.,0.]])
word_vects['tie'] = np.array([[0.,0.,0.]])

In [7]:
sent2output = np.random.rand(3,len(word_vects))
sent2output

array([[0.78447637, 0.86557059, 0.51984885, 0.63804008, 0.50309465,
        0.81376925, 0.30640475, 0.9083415 , 0.42517794],
       [0.2475017 , 0.1587508 , 0.527446  , 0.32126439, 0.19050213,
        0.13963313, 0.44999716, 0.87799952, 0.06126183],
       [0.44305521, 0.62764223, 0.79017654, 0.60289686, 0.19785308,
        0.87763954, 0.02229164, 0.9552033 , 0.98310139]])

In [6]:
identity = np.eye(3)

In [9]:
layer_0 = word_vects['red']
print(f"layer_0{layer_0}")
layer_1 = layer_0.dot(identity) + word_vects['socks']
print(f"layer_1{layer_1}")
layer_2 = layer_1.dot(identity) + word_vects['defeat']
print(f"layer_2{layer_2}")
pred = softmax(layer_2.dot(sent2output))
print(pred)

layer_0[[0. 0. 0.]]
layer_1[[0. 0. 0.]]
layer_2[[0. 0. 0.]]
[[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]]


## Backpropagation step
#### We will backprogate using two steps . First we will bprop to layer_1 as usual. Second we will also backprop to word_vects added into the layer

In [11]:
y = np.array([1,0,0,0,0,0,0,0,0]) # target one-hot vector for "yankees"
pred_delta = pred - y
pred_delta

array([[-0.88888889,  0.11111111,  0.11111111,  0.11111111,  0.11111111,
         0.11111111,  0.11111111,  0.11111111,  0.11111111]])

In [12]:
layer_2_delta = pred_delta.dot(sent2output.T)
layer_2_delta

array([[-0.14395149,  0.08298237,  0.16804032]])

In [13]:
defeat_delta = layer_2_delta * 1

In [15]:
layer_1_delta = layer_2_delta.dot(identity.T)
layer_1_delta

array([[-0.14395149,  0.08298237,  0.16804032]])

In [16]:
socks_delta = layer_1_delta * 1

In [18]:
layer_0_delta = layer_1_delta.dot(identity.T)
layer_0_delta

array([[-0.14395149,  0.08298237,  0.16804032]])

In [19]:
alpha = 0.01

In [20]:
word_vects['red'] -= layer_0_delta * alpha
word_vects['socks'] -= socks_delta * alpha
word_vects['defeat'] -= defeat_delta * alpha
identity -= np.outer(layer_0,layer_1_delta) * alpha
identity -= np.outer(layer_1,layer_2_delta) * alpha
sent2output -= np.outer(layer_2,pred_delta) * alpha

In [22]:
word_vects['socks']

array([[ 0.00143951, -0.00082982, -0.0016804 ]])