## LSTMs.

In [2]:
import numpy as np
import random

In [3]:
def generate_sequence(length, n_features):
    
    return [random.randint(0, n_features-1) for _ in range(length)]
# one hot encode sequence
def one_hot_encode(sequence, n_features):
    encoding = list()
    for value in sequence:
        
        vector = [0 for _ in range(n_features)]
        vector[value] = 1
        encoding.append(vector)
    return np.array(encoding)


In [4]:
def one_hot_decode(encoded_seq):
    return [np.argmax(vector) for vector in encoded_seq]

In [5]:
sequence = generate_sequence(25, 100)

In [6]:
one_hot = one_hot_encode(sequence,100)

In [7]:
one_hot[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
len(one_hot)

25

In [9]:
decoded = one_hot_decode(one_hot)

In [10]:
X = one_hot.reshape(1,25,100)

In [11]:
X[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
np.set_printoptions(threshold=np.nan)

In [13]:
len(X[0])

25

In [14]:
 y = one_hot[1, :] #output for lstm

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.argmax(y) # so 28 is the output

26

In [17]:
X.shape,y.shape

((1, 25, 100), (100,))

In [1]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

/Applications/anaconda/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [19]:
length = 5
n_features = 10
out_index = 2
model = Sequential()
model.add(LSTM(25, input_shape=(length, n_features)))
model.add(Dense(n_features, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 25)                3600      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                260       
Total params: 3,860
Trainable params: 3,860
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
def generate_example(length, n_features, out_index):
    # generate sequence
    sequence = generate_sequence(length, n_features)
    # one hot encode
    encoded = one_hot_encode(sequence, n_features)
    # reshape sequence to be 3D
    X = encoded.reshape((1, length, n_features))
    # select output
    y = encoded[out_index].reshape(1, n_features)
    return X,y

In [26]:
for i in range(10000):
    X , y = generate_example(length, n_features, out_index)
    model.fit(X, y, epochs=1, verbose=2)

Epoch 1/1
 - 0s - loss: 2.2036 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2330 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2851 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2274 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2786 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3990 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3656 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1522 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2603 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3592 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3768 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3558 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2751 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2982 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3821 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2135 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3341 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2564 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3511 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4170 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2671 -

In [27]:
yhat = model.predict(X)

In [29]:
np.argmax(yhat)

2

In [30]:
np.argmax(y)

2

In [ ]:
# So prediction was correct. That concludes a vanilla lstm with Keras